server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: workout-service
              uri: http://localhost:8081
              predicates:
                - Path=/workouts/**