server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: workout-service-workouts
              uri: http://workout-service:8081
#              uri: http://localhost:8081
              predicates:
                - Path=/api/workouts/**
              filters:
                - StripPrefix=1

            - id: workout-service-exercises
              uri: http://workout-service:8081
#              uri: http://localhost:8081
              predicates:
                - Path=/api/exercise-api/**
              filters:
                - StripPrefix=1

            - id: user-service
              uri: http://user-service:8082
                #              uri: http://localhost:8082
              predicates:
                - Path=/users/**

            - id: auth-service
              uri: http://auth-service:8083
                #              uri: http://localhost:8083
              predicates:
                - Path=/auth/**

security:
  jwt:
    secret-key: ${AUTH_SECURITY_JWT_SECRET_KEY:d133dec892ada8eaba7887f313d9dd11541e6c8d90413060b73039bb0b3b9aa5}
    expiration-time: ${AUTH_SECURITY_JWT_EXPIRATION_TIME:3600000}

