server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: workout-service
              uri: http://workout-service:8081
#              uri: http://localhost:8081
              predicates:
                - Path=/workouts/**
            - id: user-service
              uri: http://user-service:8082
                #              uri: http://localhost:8082
              predicates:
                - Path=/users/**
            - id: auth-service
              uri: http://auth-service:8083
                #              uri: http://localhost:8083
              predicates:
                - Path=/auth/**