server:
  port: 8082

grpc:
  server:
    port: 9002

spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5002/db}
    username: ${SPRING_DATASOURCE_USERNAME:admin_user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-migration-naming: true

security:
  jwt:
    secret-key: ${AUTH_SECURITY_JWT_SECRET_KEY:d133dec892ada8eaba7887f313d9dd11541e6c8d90413060b73039bb0b3b9aa5}
    expiration-time: ${AUTH_SECURITY_JWT_EXPIRATION_TIME:3600000}
