name: Selective Build & Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      api-gateway: ${{ steps.filter.outputs.api-gateway }}
      workout-service: ${{ steps.filter.outputs.workout-service }}
      user-service: ${{ steps.filter.outputs.user-service }}
      auth-service: ${{ steps.filter.outputs.auth-service }}
      notification-service: ${{ steps.filter.outputs.notification-service }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect changed services
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            api-gateway:
              - 'api-gateway/**'
              - 'pom.xml'
            workout-service:
              - 'workout-service/**'
              - 'pom.xml'
            user-service:
              - 'user-service/**'
              - 'pom.xml'
            auth-service:
              - 'auth-service/**'
              - 'pom.xml'
            notification-service:
              - 'notification-service/**'
              - 'pom.xml'

  generate-matrix:
    needs: detect-changes
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Generate matrix from changed services
        id: set-matrix
        run: |
          CHANGED_SERVICES=()
          if [[ "${{ needs.detect-changes.outputs.api-gateway }}" == "true" ]]; then CHANGED_SERVICES+=('"api-gateway"'); fi
          if [[ "${{ needs.detect-changes.outputs.workout-service }}" == "true" ]]; then CHANGED_SERVICES+=('"workout-service"'); fi
          if [[ "${{ needs.detect-changes.outputs.user-service }}" == "true" ]]; then CHANGED_SERVICES+=('"user-service"'); fi
          if [[ "${{ needs.detect-changes.outputs.auth-service }}" == "true" ]]; then CHANGED_SERVICES+=('"auth-service"'); fi
          if [[ "${{ needs.detect-changes.outputs.notification-service }}" == "true" ]]; then CHANGED_SERVICES+=('"notification-service"'); fi
          MATRIX="{\"service\":[${CHANGED_SERVICES[*]// /,}]}"
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  build-and-push:
    needs: generate-matrix
    if: ${{ needs.generate-matrix.outputs.matrix != '{"service":[]}' }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
      fail-fast: false
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -f ${{ matrix.service }}/Dockerfile -t $DOCKER_USER/${{ matrix.service }}:latest .
          docker push $DOCKER_USER/${{ matrix.service }}:latest
