server:
  port: 8081

spring:
  application:
    name: workout-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5001/db}
    username: ${SPRING_DATASOURCE_USERNAME:admin_user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-migration-naming: true

exercise_db_api_key: c773229263mshf8a2f2f7e190820p12f78bjsn0a64e0d743dc