server:
  port: 8081

spring:
  application:
    name: workout-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5001/db}
    username: ${SPRING_DATASOURCE_USERNAME:admin_user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-migration-naming: true

security:
  jwt:
    secret-key: ${AUTH_SECURITY_JWT_SECRET_KEY:d133dec892ada8eaba7887f313d9dd11541e6c8d90413060b73039bb0b3b9aa5}
    expiration-time: ${AUTH_SECURITY_JWT_EXPIRATION_TIME:3600000}

exercise_db_api_key: key